excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ChargeBack/ChargeBackAPI/Regex.swift
  - Pods
  - ChargeBack/Flow/Storyboards.swift 

force_cast: warning # implicitly
