excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ChargeBack/ThirdParty/Regex.swift
  - Pods
  - ChargeBack/ThirdParty/Storyboards.swift 

force_cast: warning # implicitly
