import_from_git(url: 'git@bitbucket.org:ant_one/fastlane_keys.git', path: 'keys/fastlane_keys')
import_from_git(url: 'git@github.com:barrault01/my_fastlane_lanes.git', path: 'fastlane/Fastfile')

fastlane_version "2.3.0"

default_platform :ios

def pod_name
  "ChargeBack"
end


def changelogFile 
 "../CHANGELOG.md"
end


def proj
{
    plist: "./#{pod_name}/Info.plist",
    xcodeproj: "./#{pod_name}.xcodeproj/",
    repo_url: "http://bitbucket.org/antoinebarrault/nubank-chargeback-ios",
    scheme: "#{pod_name}-pod",
}
end

def cocoapods 
{
    private_repo: "my-private-cocoapods-repository",
    private_repo_name: "my-private-cocoapods-repository",
    private_repo_git_url: "git@bitbucket.org:ant_one/my-private-cocoapods-repository.git",
    podspec: "./#{pod_name}.podspec",
    pod_name: "#{pod_name}"
}
end

#End share func to use lanes on ios_fastlane_keys.git



platform :ios do 

lane :metrics do
    scan(scheme: proj[:scheme], code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./reports")
    slather(cobertura_xml: true, jenkins: true, scheme: proj[:scheme], build_directory: "./DerivedData", output_directory: "./reports", proj: proj[:xcodeproj])
    sh("cd .. && lizard ./[SOURCE_FOLDER] -l swift --xml > ./reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    # version_number = get_info_plist_value(path: proj[:plist], key: 'CFBundleShortVersionString')
    # sonar(project_version:version_number)
end


 after_all do |lane|
   notification(message:"Finished lane: #{lane}")
 end
 
 error do |lane, exception|
   notification(subtitle: "Erro in lane: #{lane}", message:"Erro in lane: #{exception}")
 end
 
end

